import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { MotionLazy } from "@/components/animate/motion-lazy";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App  11212",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MotionLazy>{children}</MotionLazy>
      </body>
    </html>
  );
}
